const products = [
    {
        id: 0,
        name: "Chandelier",
        price: 500.00,
        instock: 1,
        description: 'This art deco inspired chandelier is 44" x 24" and would make a great addition to any dining or living room!',
        imgSrc: "img/chandelier.jpeg",
    },
    {
        id: 1,
        name: "Painting By Tutu",
        price: 150.00,
        instock: 1,
        description: 'This 27" x 23" work of art was painted by a local artist and titled "Family Choas". We all need a little more chaos in our lives!',
        imgSrc: "img/painting.jpeg",
    },
    {
        id: 2,
        name: "Porcelain Vases",
        price: 100.00,
        instock: 1,
        description: `Each vase measures 23" x 12". Unfortunately, they are not vintage, but shh we don't have to tell.`,
        imgSrc: "img/porcelainvases.jpeg",
    },
    {
        id: 3,
        name: "Quartz Geode",
        price: 30.00,
        instock: 1,
        description: 'Perfect for any geology lovers in your life that also have a flair for the dramatic. This pedestaled rock measures at 10" x 6".',
        imgSrc: "img/quartz.jpeg",
    },
    {
        id: 4,
        name: "Mona Lisa Paintings",
        price: 75.00,
        instock: 1,
        description: 'Who needs the stuffy old Mona Lisa when you could have a flower child and a pirate, arrr! Did I mention they are true Parisian paintings from Paris? The Dimensions are 8" x 8" and 23" x 12".',
        imgSrc: "img/monas.jpeg",
    },
    {
        id: 5,
        name: "Decanter",
        price: 100.00,
        instock: 1,
        description: 'The golfer in your life will thank you for this one. Make sure they were old enoough to play in 1986 though before they go telling stories about playing with Tiger.',
        imgSrc: "img/decanter.jpeg",
    },
];